version: '3.7'

services:

  back-end:
    image: siilisalabs/epimetheus-backend:latest
    ports:
    - "5000:5000"
    env_file:
    - ${ENV_FILE}
    container_name: backend-server

  front-end:
    tty: yes
    image: siilisalabs/epimetheus-frontend:latest
    ports:
    - "3000:8080"
    volumes:
      - ./frontend/src:/app/src
    container_name: frontend-server
