export const colorTypes = {
    'gradient black': '#141312',
    'evidence grey': '#77716b',
    'evidence-grey-lighter': '#adaaa6',
    'evidence grey darker': '#6b6661',
    'nero white': '#ffffff',
    'nelson purple': '#b8557b',
    'semolina red': '#C63757',
    'pirlo blue': '#067cc1',
    'pirlo blue darker': '#0469a4',
    'titan green': '#238564',
    'titan green darker': '#16815d',
    'titan green darkest': '#145B43',
    'kumpula yellow': '#FAF3E1',
    'toukola green': '#E9F5E1',
    'toukola green lighter': '#F4F7F2',
    'vallila blue': '#E1F1F7',
    'hermanni grey': '#eeecec',
    'hermanni grey lighter': '#F8F8F7',
    'arabia red': '#faecec',
    'tonic grey': '#d7d4d3',
    'sparkling blue': '#80bfdb',
    'birra brown': '#976F10',
};
