export const colorTypes = {
    'gradient black': '#141312',
    'evidence grey': '#77716b',
    'evidence-grey-lighter': '#adaaa6',
    'evidence grey darker': '#6b6661',
    'nero white': '#ffffff',
    'nelson purple': '#b8557b',
    'semolina red': '#c63757',
    'pirlo blue': '#067cc1',
    'pirlo blue darker': '#0469a4',
    'titan green': '#238564',
    'titan green darker': '#16815d',
    'titan green darkest': '#145b43',
    'kumpula yellow': '#faf3e1',
    'toukola green': '#e9f5e1',
    'toukola green lighter': '#f4f7f2',
    'vallila blue': '#e1f1f7',
    'hermanni grey': '#eeecec',
    'hermanni grey lighter': '#f8f8f7',
    'arabia red': '#faecec',
    'tonic grey': '#d7d4d3',
    'sparkling blue': '#80bfdb',
    'birra brown': '#976f10',
};
