export const colorTypes = {
    'gradient black': '#141312',
    'evidence grey': '#7B756F',
    'nero white': '#ffffff',
    'nelson purple': '#b8557b',
    'semolina red': '#C63757',
    'pirlo blue': '#067cc1',
    'titan green': '#238564',
    'kumpula yellow': '#FAF3E1',
    'toukola green': '#E9F5E1',
    'vallila blue': '#E1F1F7',
    'hermanni grey': '#EDECEC',
    'arabia red': '#faecec',
    'tonic grey': '#d7d4d3',
    'sparkling blue': '#80bfdb',
};
