name: build-front-end
on:
  push:
#    branches:
#      - master
#    paths:
#      - "backend_server/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build back-end
        id: acr-back-end
        uses: ams0/acr-task-github-action@master
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          #image: testmanager2.0-backend
          image: testing-gh-actions
          folder: backend_server
          dockerfile: ../../backend_server/Dockerfile