name: publish-to-docker-hub
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: ./Dockerfile-prod
          push: true
          tags: siilisalabs/epimetheus-frontend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: ./Dockerfile
          push: true
          tags: siilisalabs/epimetheus-backend:latest
      